I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 314, in script call
    call checktime
  File "game/script.rpy", line 914, in script
    $ inventory.add_item(Theal)
  File "game/script.rpy", line 914, in <module>
    $ inventory.add_item(Theal)
NameError: name 'Theal' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 314, in script call
    call checktime
  File "game/script.rpy", line 914, in script
    $ inventory.add_item(Theal)
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 914, in <module>
    $ inventory.add_item(Theal)
NameError: name 'Theal' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CyberDzban 0.0000000008
Thu Feb 29 19:37:59 2024
