I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/akt2.rpy", line 129, in script call
    call checktime
  File "game/script.rpy", line 90, in script
    return
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/akt2.rpy", line 129, in script call
    call checktime
  File "game/script.rpy", line 90, in script
    return
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.00000001
Tue Aug 27 13:30:49 2024
