I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 788, in script
    if vron < 1:
  File "game/script.rpy", line 788, in <module>
    if vron < 1:
NameError: name 'vron' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 788, in script
    if vron < 1:
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 788, in <module>
    if vron < 1:
NameError: name 'vron' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CyberDzban 0.0000000001
Sun Nov 12 21:23:25 2023
