I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 206, in script call
    call testCech(BC, 5)
  File "game/script.rpy", line 79, in script
    label testCech(cecha, PT):
  File "game/script.rpy", line 206, in <module>
    call testCech(BC, 5)
NameError: name 'BC' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 206, in script call
    call testCech(BC, 5)
  File "game/script.rpy", line 79, in script
    label testCech(cecha, PT):
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1421, in execute
    args, kwargs = self.arguments.evaluate()
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\parameter.py", line 477, in evaluate
    value = renpy.python.py_eval(v, locals=scope)
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Lenovo\Desktop\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 206, in <module>
    call testCech(BC, 5)
NameError: name 'BC' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.0000000009
Wed Mar 27 08:07:34 2024
