I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2724, in script call
    call checkHP(7) from _call_checkHP
  File "game/script.rpy", line 176, in script
    $ wybrany_dzwiek = random.choice(buul)
  File "game/script.rpy", line 176, in <module>
    $ wybrany_dzwiek = random.choice(buul)
NameError: name 'random' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2724, in script call
    call checkHP(7) from _call_checkHP
  File "game/script.rpy", line 176, in script
    $ wybrany_dzwiek = random.choice(buul)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 176, in <module>
    $ wybrany_dzwiek = random.choice(buul)
NameError: name 'random' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
CyberDzban 0.00000001
Sat Sep 28 10:45:59 2024
