I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1399, in script
    $ cel = renpy.random.radint(1,3)
  File "game/script.rpy", line 1399, in <module>
    $ cel = renpy.random.radint(1,3)
AttributeError: 'DetRandom' object has no attribute 'radint'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1399, in script
    $ cel = renpy.random.radint(1,3)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1399, in <module>
    $ cel = renpy.random.radint(1,3)
AttributeError: 'DetRandom' object has no attribute 'radint'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CyberDzban 0.0000000005
Mon Nov 27 22:22:40 2023
