I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 332, in script call
    call bigunl
  File "game/bigunl.rpy", line 7, in script
    while cnt < foty:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 332, in script call
    call bigunl
  File "game/bigunl.rpy", line 7, in script
    while cnt < foty:
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.000000008
Mon Aug  5 23:47:40 2024
